# ??????
spring:
  application:
    name: clothesOJ-backend
  # ?? dev ??
  profiles:
    active: dev
  # ?? swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session ??
    session:
  #    store-type: redis
  #    # 30 ???
      timeout: 2592000
  # ?????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ClothesOJ
    username: root
    password: "00000000"
  # Redis ??
#  redis:
#    database: 1
#    host: localhost
#    port: 6379
#    timeout: 5000
#    password: "00000000"
server:
  address: 0.0.0.0
  port: 8121
  servlet:
    context-path: /api
    # cookie 30 ???
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 逻辑删除
      logic-delete-value: 1 # 表示已经删除
      logic-not-delete-value: 0 # 未删除
#代码沙箱类型
codesandbox:
  type: remote